// The @gmod/vcf genotype-scan before/after: v7.1.1 against v7.2.0, one process
// per side.
//
// Why this is not a vitest bench like everything else here. vitest runs both
// sides of a comparison in one process, so they share inline caches at every
// call site they both reach — `parseLine`, the genotype callback, `charCodeAt`
// on two different string representations. Each side is then slower than it
// would be alone, and not by the same amount. At the 6x-45x differences
// vcf.bench.ts measures that is noise. At the ~1.1x this change makes on a
// GT-only file it inverts the answer: in-process, the 3000-sample GT-only case
// reports 0.88x, a regression that does not exist.
//
// So: one process per arm, arms alternating so machine drift lands on both, each
// arm reporting its own best-of-N and the driver taking the median across
// rounds. A checksum crosses the process boundary with the timing and the driver
// refuses to print a speedup if the two sides disagree.
//
//   node --experimental-strip-types scan.ts            # driver
//   node --experimental-strip-types scan.ts --arm old|new <file>
import { execFileSync } from 'node:child_process'
import { mkdirSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

import { VCF_CASES, vcfParts } from './lib/corpus.ts'

const SELF = fileURLToPath(import.meta.url)
const ROUNDS = 7
const INNER = 9

// ------------------------------------------------------------------- arm ---

if (process.argv[2] === '--arm') {
  const side = process.argv[3] as 'old' | 'new'
  const file = process.argv[4]!
  // Only one build is ever imported in this process; that is the whole point.
  const { default: VCF } = await import(
    side === 'old'
      ? './.libs/vcf-js-scan/old/esm/index.js'
      : './.libs/vcf-js-scan/new/esm/index.js'
  )
  const { header, lines } = vcfParts(file)
  const parser = new (VCF as any)({ header })

  // The consumer JBrowse's genotype matrices run: a range per sample, no
  // substring materialized. Summing the lengths keeps it honest — the callback
  // has to actually receive the range — while costing almost nothing itself, so
  // the number is the scan.
  function pass() {
    let sum = 0
    for (const line of lines) {
      parser
        .parseLine(line)
        .processGenotypes((_s: string, a: number, b: number) => {
          sum = (sum * 31 + (b - a)) % 1_000_000_007
        })
    }
    return sum
  }

  const checksum = pass()
  pass()
  const ts: number[] = []
  for (let i = 0; i < INNER; i++) {
    const t = performance.now()
    pass()
    ts.push(performance.now() - t)
  }
  ts.sort((a, b) => a - b)
  // best-of-N: on a shared box the minimum is the least contaminated estimate
  console.log(`${ts[0]!.toFixed(4)} ${checksum}`)
  process.exit(0)
}

// ---------------------------------------------------------------- driver ---

function arm(side: 'old' | 'new', file: string) {
  const out = execFileSync(
    process.execPath,
    ['--experimental-strip-types', SELF, '--arm', side, file],
    { encoding: 'utf8' },
  ).trim()
  const [ms, checksum] = out.split(' ')
  return { ms: Number(ms), checksum }
}

const median = (xs: number[]) => [...xs].sort((a, b) => a - b)[xs.length >> 1]!

interface Result {
  case: string
  samples: number
  shape: string
  old: number
  new: number
  ratio: number
  identical: boolean
}

const results: Result[] = []
console.log(`@gmod/vcf v7.1.1 -> v7.2.0, ${ROUNDS} rounds x best-of-${INNER}\n`)
console.log(
  `${'case'.padEnd(22)}${'v7.1.1'.padStart(11)}${'v7.2.0'.padStart(11)}${'ratio'.padStart(9)}  agree`,
)
console.log('-'.repeat(60))

for (const { label, file, samples, shape } of VCF_CASES) {
  const olds: number[] = []
  const news: number[] = []
  let oc = ''
  let nc = ''
  for (let r = 0; r < ROUNDS; r++) {
    const o = arm('old', file)
    olds.push(o.ms)
    oc = o.checksum!
    const n = arm('new', file)
    news.push(n.ms)
    nc = n.checksum!
  }
  const o = median(olds)
  const n = median(news)
  const identical = oc === nc
  results.push({
    case: label,
    samples,
    shape,
    old: o,
    new: n,
    ratio: o / n,
    identical,
  })
  console.log(
    `${label.padEnd(22)}${`${o.toFixed(2)} ms`.padStart(11)}${`${n.toFixed(2)} ms`.padStart(11)}` +
      `${`${(o / n).toFixed(2)}x`.padStart(9)}  ${identical ? 'yes' : 'NO'}`,
  )
}

mkdirSync(new URL('results/', import.meta.url), { recursive: true })
writeFileSync(
  new URL('results/vcf-scan.json', import.meta.url),
  JSON.stringify({ rounds: ROUNDS, inner: INNER, results }, null, 2),
)

const md = [
  '# @gmod/vcf genotype scan: v7.1.1 to v7.2.0',
  '',
  'Generated by `make scan`. One process per side, arms alternating, each arm',
  `reporting its own best-of-${INNER} and the table the median over ${ROUNDS} rounds.`,
  'The checksum column is the genotype ranges both sides reported, folded; it has',
  'to match or the timing means nothing.',
  '',
  '| case | v7.1.1 | v7.2.0 | speedup | ranges agree |',
  '| --- | --- | --- | --- | --- |',
  ...results.map(
    r =>
      `| ${r.case} | ${r.old.toFixed(2)} ms | ${r.new.toFixed(2)} ms | ` +
      `${r.ratio.toFixed(2)}x | ${r.identical ? 'yes' : 'NO'} |`,
  ),
  '',
  'The split between the two shapes is the change working as designed. `wide`',
  '(`FORMAT=GT:AD:DP:GQ:PL`) is where GT is followed by fields the scan has to',
  'step over to reach the next sample, and 7.2.0 hops them with one `indexOf`',
  'instead of a `charCodeAt` loop. `gtonly` (`FORMAT=GT`, the 1000 Genomes phase',
  '3 shape) has nothing between samples to skip, so that path was deliberately',
  'left alone — `indexOf` measured slower there — and what it still gains comes',
  'from the second half of the change: scanning the flat line with offsets rather',
  'than a `line.slice()`, whose V8 SlicedString costs an unwrap on every',
  '`charCodeAt`.',
  '',
].join('\n')
writeFileSync(new URL('results/vcf-scan.md', import.meta.url), md)
console.log('\nwrote results/vcf-scan.md and results/vcf-scan.json')
